apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-helm-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/diarhusseindevo/helm-charts.git
    targetRevision: main
    path: simple-helm-app
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
